perform_sweep: True
paths:
  model_note: Sweep_example
parameter_space:

  # Number of different runs
  seed: !sweep
    default: 0
    range: [100]

  num_epochs: 1000

  RC_circuit:
    Data:
      load_from_dir: data/RC_circuit/Example_data/data.h5
    Training:
      batch_size: 50

    NeuralNet:
      prior:
        distribution: uniform
        parameters:
          lower: 0.5
          upper: 5