Data:
  synthetic_data:

    # Length of time series
    num_steps: 100

    # True values for R and C
    R: !is-positive 1.2
    C: !is-positive 1.2

    # Distributions for the initial values of the temperatures and Q values
    initial_conditions:
      T_in:
        distribution: uniform
        parameters:
          lower: 270
          upper: 290
      T_out:
        distribution: uniform
        parameters:
          lower: 270
          upper: 290
      Q_H:
        distribution: uniform
        parameters:
          lower: -0.1
          upper: 0.1
      Q_O:
        distribution: uniform
        parameters:
          lower: -0.1
          upper: 0.1

    # Variance for the fluctuation of T_out:
    T_out_std: !is-positive-or-zero 0.1

    # Variance for the fluctuation of Q:
    Q_std: !is-positive-or-zero 0.05

  # Time differential to use
  dt: 0.01

# Settings for the neural network
NeuralNet:
  num_layers: !is-positive-int 3
  nodes_per_layer:
    default: !is-positive-int 20
  biases:
    default: [0, 1]
  activation_funcs:
    default: sigmoid
    layer_specific:
      -1: abs
  learning_rate: !is-positive 0.002

# Settings for the training
Training:
  batch_size: !is-positive-int 1
  loss_function:
    name: MSELoss
    kwargs:
      reduction: sum
  to_learn: [ R, C ]
  device: cpu
  num_threads: ~

  # Can scale parameters here
  scaling_factors:
    C: 1
    R: 1
