Data:
  load_from_dir:
    path: data/Migration/UN_migration_estimates_country_area.h5
    time_isel: -1
    sf: 1.0

# Neural network configuration
NeuralNet:
  num_layers: 2
  nodes_per_layer:
    default: 20
  biases:
    default: ~
  activation_funcs:
    default: tanh
    layer_specific:
      -1: abs
  learning_rate: !is-positive 0.002

Training:
  loss_function:
    name: MSELoss
    kwargs:
      reduction: sum
  device: cpu
